'use client';
import {useEffect,useState} from 'react';
import {defaultPermissions,permissionLabels,roleLabels} from '../lib/permissions';
async function send(url:string,body:any){const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data:any=await res.json();if(!res.ok)throw Error(data.error??'Não foi possível salvar.');return data;}
export async function logout(){await send('/api/auth',{action:'logout'});window.location.reload();}
export function AuthGate({children}:{children:React.ReactNode}){
 const [state,setState]=useState<any>(null),[mode,setMode]=useState('login'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{fetch('/api/auth',{cache:'no-store'}).then(r=>r.json()).then(setState).catch(()=>setError('Não foi possível conectar. Recarregue a página.'));},[]);
 if(state?.user)return children;
 return <main className="auth-screen"><section className="auth-card"><span className="brand-icon">A</span><p className="eyebrow">EEEFM ANTONIO DO SANTOS NEVES</p><h1>ASN Projetos</h1><p>Acompanhe as atividades e avaliações da sua turma.</p>{state&&<><div className="tabs"><button onClick={()=>setMode('login')} className={mode==='login'?'selected':''}>Entrar</button>{state.registrationOpen&&<button onClick={()=>setMode('register')} className={mode==='register'?'selected':''}>Solicitar cadastro</button>}</div><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');const values=Object.fromEntries(new FormData(e.currentTarget));try{const result=await send('/api/auth',{...values,action:mode});if(mode==='login')window.location.reload();else{setMessage(result.message);setMode('login');}}catch(e){setError(String((e as Error).message));}finally{setBusy(false);}}}>
 {mode==='register'&&<label className="field">Nome completo<input name="name" required maxLength={150} autoComplete="name"/></label>}<label className="field">E-mail<input name="email" type="email" required autoComplete="username" maxLength={200}/></label><label className="field">Senha<input name="password" type="password" required minLength={10} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'}/></label><button className="primary-link" disabled={busy}>{busy?'Aguarde…':mode==='login'?'Entrar no sistema':'Enviar solicitação'}</button></form>{!state.registrationOpen&&<small>Para obter acesso, solicite seu cadastro ao administrador.</small>}</>}{!state&&!error&&<p>Conectando…</p>}{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}</section></main>;
}
export function AccountPassword(){const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);return <section className="panel"><h2>Minha senha</h2><form className="account-form" onSubmit={async e=>{e.preventDefault();const f=e.currentTarget;setBusy(true);try{await send('/api/auth',{action:'password',...Object.fromEntries(new FormData(f))});await logout();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}><label className="field">Senha atual<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label className="field">Nova senha<input name="password" type="password" autoComplete="new-password" required minLength={10} maxLength={128}/></label><button className="primary-link" disabled={busy}>Alterar senha e entrar novamente</button><p role="status">{message}</p></form></section>;}
export function UserManager(){
 const [users,setUsers]=useState<any[]>([]),[open,setOpen]=useState(false),[form,setForm]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/users',{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error);setUsers(d.users);setOpen(d.registrationOpen);}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function act(b:any){setBusy(true);setMessage('');try{await send('/api/users',b);await load();setForm(null);setMessage('Alterações salvas. As permissões passam a valer imediatamente.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><div className="section-title"><div><h2>Usuários e permissões</h2><p>Aprove cadastros e escolha as páginas e ações de cada pessoa.</p></div><button className="primary-link" onClick={()=>setForm({name:'',email:'',role:'representative',status:'active',permissions:[],password:''})}>Cadastrar usuário</button></div><label className="permission-check"><input type="checkbox" checked={open} disabled={busy} onChange={e=>act({action:'registration',open:e.target.checked})}/>Permitir solicitações de cadastro na tela de entrada</label><p className="muted">Solicitações ficam pendentes até sua aprovação. Avaliadores e representantes também precisam dos vínculos de turma, grupo e área em Cadastros. Coordenadores abrangem todas as turmas; administradores têm acesso completo.</p><p role="status">{message}</p>
 <div className="table-wrap"><table><thead><tr><th>Usuário</th><th>Perfil</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}<small>{u.email}</small></td><td>{roleLabels[u.role]}</td><td>{{active:'Ativo',pending:'Aguardando aprovação',blocked:'Bloqueado'}[u.status as string]}</td><td><button className="text-button" onClick={()=>setForm({...u,permissions:JSON.parse(u.permissions),password:''})}>Editar acesso</button>{u.email!=='welber05@gmail.com'&&<button className="text-button" onClick={()=>{if(window.confirm('Excluir a conta de '+u.name+'? O histórico escolar será preservado.'))act({action:'delete',id:u.id});}}>Excluir conta</button>}</td></tr>)}</tbody></table></div>
 {form&&<form className="account-editor" onSubmit={e=>{e.preventDefault();act({action:'save',...form});}}><h3>{form.id?'Editar usuário':'Novo usuário'}</h3><div className="form-grid"><label className="field">Nome<input required maxLength={150} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field">E-mail<input type="email" required disabled={!!form.id} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="field">Perfil<select value={form.role} onChange={e=>setForm({...form,role:e.target.value,permissions:defaultPermissions[e.target.value]})}>{Object.entries(roleLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field">Situação<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Ativo / aprovado</option><option value="pending">Pendente</option><option value="blocked">Bloqueado</option></select></label><label className="field">{form.id?'Nova senha (opcional)':'Senha inicial'}<input type="password" autoComplete="new-password" required={!form.id} minLength={10} maxLength={128} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label></div>
 {form.role==='admin'?<p>Administradores podem acessar todas as páginas e funções, inclusive gerenciar usuários.</p>:<><h3>Páginas do menu e funções permitidas</h3><p>Marque a página para visualização e, separadamente, as ações que deseja liberar. As permissões respeitam os grupos e áreas vinculados ao perfil.</p><div className="permission-grid">{Object.entries(permissionLabels).map(([k,label])=><label className="permission-check" key={k}><input type="checkbox" checked={form.permissions.includes(k)} onChange={e=>setForm({...form,permissions:e.target.checked?[...form.permissions,k]:form.permissions.filter((p:string)=>p!==k)})}/>{label}</label>)}</div></>}
 <div className="row-actions"><button className="primary-link" disabled={busy}>Salvar permissões</button><button type="button" onClick={()=>setForm(null)}>Cancelar</button></div></form>}
 </section>;
}
