'use client';
import {useEffect,useState,useMemo} from 'react';
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid,LineChart,Line,Legend} from 'recharts';
import {LayoutDashboard,CalendarDays,ListChecks,Users,FileText,ClipboardCheck,GraduationCap,Settings2,Plus,Download,RefreshCw,Check,ArrowUpRight,Pencil,Trash2,X,LogOut,Upload,BookOpen} from 'lucide-react';
import {Button} from '../components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '../components/ui/dialog';
import {emptyData,stages,statuses,defaultConfig,validateConfig,percentScore,studentGrade,groupStage} from '../lib/model';
type Row=Record<string,any>;
const fmt=(v:string|null)=>v?new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'}):'Não registrado';
const day=(v:string)=>v?new Date(v+'T12:00:00Z').toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—';
const num=(v:number|null,decimal=2)=>v===null||v===undefined?'—':v.toLocaleString('pt-BR',{maximumFractionDigits:decimal,minimumFractionDigits:decimal});
const monday=()=>{const d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7));return d.toISOString().slice(0,10);};
const nav=[['dashboard','Visão geral',LayoutDashboard],['weeks','Semanas e entregas',CalendarDays],['tasks','Atividades individuais',ListChecks],['written','Trabalho escrito',FileText],['assessments','Fichas de avaliação',ClipboardCheck],['grades','Notas do trimestre',GraduationCap],['registry','Cadastros',Users],['rubrics','Parâmetros de notas',Settings2]] as const;
function Badge({status,children}:{status?:string,children?:any}){return <span className={'badge '+(status??'pending')}>{children??statuses[status??'pending']}</span>;}
function Field({label,children}:{label:string,children:any}){return <label className="field"><span>{label}</span>{children}</label>;}
function Empty({children}:{children:any}){return <div className="empty"><BookOpen size={28}/><p>{children}</p></div>;}
function exportCSV(name:string,rows:Row[]){if(!rows.length)return;const keys=Object.keys(rows[0]);const esc=(v:any)=>{let s=String(v??'');if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const blob=new Blob(['\uFEFF'+[keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(esc).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name+'.csv';a.click();URL.revokeObjectURL(url);}
export default function Workspace(){
 const [d,setD]=useState<any>(emptyData),[tab,setTab]=useState('dashboard'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[authRequired,setAuthRequired]=useState(false),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[updated,setUpdated]=useState('');
 const [classId,setClassId]=useState('class-3'),[groupId,setGroupId]=useState(''),[weekId,setWeekId]=useState(''),[studentId,setStudentId]=useState(''),[status,setStatus]=useState(''),[search,setSearch]=useState(''),[registry,setRegistry]=useState('students'),[modal,setModal]=useState<Row|null>(null),[form,setForm]=useState<Row>({});
 const [total,setTotal]=useState(''),[config,setConfig]=useState<any>(defaultConfig());
 const admin=d.user.admin;
 async function load(initial=false){try{if(initial)setLoading(true);let res=await fetch('/api/data',{cache:'no-store'}),data:any=await res.json();if(data.needsInitialization){const init=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'initialize'})});if(!init.ok)throw Error(((await init.json()) as any).error);res=await fetch('/api/data',{cache:'no-store'});data=await res.json();}if(!res.ok){setAuthRequired(!!data.authRequired);throw Error(data.error);}setD(data);setError('');setUpdated(new Date().toISOString());return data;}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar.');}finally{setLoading(false);}}
 useEffect(()=>{load(true);const timer=setInterval(()=>load(),30000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{const r=d.rubrics.find((r:Row)=>r.class_id===classId);setTotal(r?String(r.total):'');setConfig(r?JSON.parse(r.config):defaultConfig());},[classId,d.rubrics.find((r:Row)=>r.class_id===classId)?.updated_at]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const control=new AbortController();Promise.resolve(context.registerTool({name:'show_project_area',title:'Abrir área do acompanhamento',description:'Abre uma área do sistema sem alterar registros.',inputSchema:{type:'object',properties:{area:{type:'string',enum:nav.map(n=>n[0])}},required:['area'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:any)=>{if(!nav.some(n=>n[0]===input.area))throw Error('Área inválida.');setTab(input.area);return {area:input.area};}},{signal:control.signal})).catch(()=>{});return()=>control.abort();},[]);
 const groups=d.groups.filter((g:Row)=>!classId||g.class_id===classId),students=d.students.filter((s:Row)=>(!classId||s.class_id===classId)&&(!groupId||s.group_id===groupId)),weeks=d.weeks.filter((w:Row)=>!classId||w.class_id===classId).sort((a:Row,b:Row)=>a.start.localeCompare(b.start));
 useEffect(()=>{if(d.classes.length&&!d.classes.some((c:Row)=>c.id===classId)){setClassId(d.classes[0].id);setGroupId('');setWeekId('');setStudentId('');}},[d.classes,classId]);
 const selectedGroups=groups.filter((g:Row)=>(!groupId||g.id===groupId)),selectedWeeks=weeks.filter((w:Row)=>!weekId||w.id===weekId);
 const name=(table:string,id:string)=>d[table].find((r:Row)=>r.id===id)?.name??'—';
 const reports=d.reports.filter((r:Row)=>selectedGroups.some((g:Row)=>g.id===r.group_id)&&selectedWeeks.some((w:Row)=>w.id===r.week_id));
 const tasks=d.tasks.filter((t:Row)=>reports.some((r:Row)=>r.id===t.report_id)&&(!studentId||t.student_id===studentId)&&(!status||t.status===status)&&(!search||(name('students',t.student_id)+' '+t.description).toLowerCase().includes(search.toLowerCase())));
 const matrix=selectedWeeks.flatMap((w:Row)=>selectedGroups.filter((g:Row)=>g.active===1&&w.start>=g.start_week).map((g:Row)=>{const r=d.reports.find((r:Row)=>r.week_id===w.id&&r.group_id===g.id);const t=d.tasks.filter((t:Row)=>t.report_id===r?.id);return {w,g,r,t,checked:!!r?.reviewed_at&&t.every((t:Row)=>t.status==='none'||t.reviewed_at),late:Date.parse(w.due_at)<Date.now()};}));
 const done=tasks.filter((t:Row)=>t.status==='done').length,missed=tasks.filter((t:Row)=>t.status==='missed').length,pending=tasks.filter((t:Row)=>t.status==='pending').length;
 const chartData=selectedGroups.map((g:Row)=>{const ids=d.reports.filter((r:Row)=>r.group_id===g.id&&selectedWeeks.some((w:Row)=>w.id===r.week_id)).map((r:Row)=>r.id);const ts=tasks.filter((t:Row)=>ids.includes(t.report_id));return {name:g.name,Cumpriu:ts.filter((t:Row)=>t.status==='done').length,'Não cumpriu':ts.filter((t:Row)=>t.status==='missed').length,'A conferir':ts.filter((t:Row)=>t.status==='pending').length};});
 const trend=selectedWeeks.map((w:Row)=>{const rs=reports.filter((r:Row)=>r.week_id===w.id),ts=tasks.filter((t:Row)=>rs.some((r:Row)=>r.id===t.report_id)),v=ts.filter((t:Row)=>t.percent!==null);return {name:day(w.start).slice(0,5),'Desempenho (%)':v.length?v.reduce((s:number,t:Row)=>s+t.percent,0)/v.length:null};});
 const canWeekly=(g:string)=>admin||d.assignments.some((a:Row)=>a.active===1&&a.group_id===g&&a.stage==='weekly'&&d.evaluators.some((e:Row)=>e.id===a.evaluator_id&&e.email===d.user.email));
 async function act(payload:Row,close=true){setBusy(true);setError('');try{const res=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body:any=await res.json();if(!res.ok)throw Error(body.error);await load();if(close)setModal(null);setNotice('Registro salvo.');setTimeout(()=>setNotice(''),4000);return true;}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.');return false;}finally{setBusy(false);}}
 function open(type:string,row?:Row,extra:Row={}){setError('');setModal({type,row,...extra});if(type==='review')setForm({status:row?.status==='pending'?'done':row?.status,percent:row?.percent??'',justification:row?.justification??'',evidence:row?.evidence??''});else if(type==='report')setForm({groupId:row?.group_id??extra.groupId??groupId??'',weekId:row?.week_id??extra.weekId??weekId??'',past:row?.past??'',plan:row?.plan??'',delivery:row?.delivery??'',tasks:row?Object.fromEntries(d.tasks.filter((t:Row)=>t.report_id===row.id).map((t:Row)=>[t.student_id,{description:t.description,none:t.status==='none'}])):{}});else if(type==='assessment')setForm({scores:{},notes:''});else setForm({...row,due_at:row?.due_at?new Date(Date.parse(row.due_at)-3*3600000).toISOString().slice(0,16):undefined,classId:row?.class_id??classId,groupId:row?.group_id??'',grade:row?.grade??3,year:row?.year??2026,start:row?.start??monday(),end:monday(),startWeek:row?.start_week??monday(),stage:row?.stage??'written',evaluatorId:row?.evaluator_id??''});}
 function set(k:string,v:any){setForm(f=>({...f,[k]:v}));}
 const filters=<div className="filters"><Field label="Turma"><select value={classId} onChange={e=>{setClassId(e.target.value);setGroupId('');setWeekId('');setStudentId('');}}>{d.classes.map((c:Row)=><option key={c.id} value={c.id}>{c.name} · {c.year}{c.active===0?' (inativa)':''}</option>)}</select></Field><Field label="Grupo"><select value={groupId} onChange={e=>{setGroupId(e.target.value);setStudentId('');}}><option value="">Todos os grupos</option>{groups.map((g:Row)=><option key={g.id} value={g.id}>{g.name}</option>)}</select></Field><Field label="Semana"><select value={weekId} onChange={e=>setWeekId(e.target.value)}><option value="">Todas as semanas</option>{weeks.map((w:Row)=><option key={w.id} value={w.id}>{day(w.start)}</option>)}</select></Field><Field label="Estudante"><select value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Todos os estudantes</option>{students.map((s:Row)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field></div>;
 const taskRows=tasks.map((t:Row)=>{const r=d.reports.find((r:Row)=>r.id===t.report_id),w=d.weeks.find((w:Row)=>w.id===r.week_id);return {...t,student:name('students',t.student_id),group:name('groups',r.group_id),week:w.start,groupId:r.group_id};});
 const rubric=d.rubrics.find((r:Row)=>r.class_id===classId);
 const locked=d.assessments.some((a:Row)=>d.assignments.some((x:Row)=>x.id===a.assignment_id&&groups.some((g:Row)=>g.id===x.group_id)))||d.tasks.some((t:Row)=>t.reviewed_at&&d.reports.some((r:Row)=>r.id===t.report_id&&groups.some((g:Row)=>g.id===r.group_id)))||d.reports.some((r:Row)=>r.reviewed_at&&groups.some((g:Row)=>g.id===r.group_id));
 const gradeRows=students.filter((s:Row)=>(!studentId||s.id===studentId)).map((s:Row)=>({s,grade:studentGrade(d,s)}));
 const stageLabel=(s:string)=>stages.find(x=>x.id===s)?.name??s;
 async function submit(e:React.FormEvent){e.preventDefault();if(!modal)return;const type=modal.type,row=modal.row;
 if(type==='review')return void act({action:modal.table==='tasks'?'review-task':'review-report',id:row.id,updatedAt:row.updated_at,...form,percent:form.percent===''?'':Number(form.percent)});
 if(type==='report'){const members=d.students.filter((s:Row)=>s.group_id===form.groupId&&s.active===1);return void act({action:row?'update-report':'report',id:row?.id,updatedAt:row?.updated_at,...form,tasks:members.map((s:Row)=>({studentId:s.id,...(form.tasks[s.id]??{})}))});}
 if(type==='assessment'){const file=d.files.filter((f:Row)=>f.group_id===row.group_id).sort((a:Row,b:Row)=>b.uploaded_at.localeCompare(a.uploaded_at))[0];return void act({action:'assessment',assignmentId:row.id,fileId:file?.id,...form});}
 if(type==='upload'){setBusy(true);try{const fd=new FormData();fd.append('groupId',form.groupId);fd.append('file',form.file);const res=await fetch('/api/files',{method:'POST',body:fd});const data:any=await res.json();if(!res.ok)throw Error(data.error);await load();setModal(null);setNotice('Trabalho escrito enviado.');}catch(e){setError(e instanceof Error?e.message:'Falha no envio.');}finally{setBusy(false);}return;}
 if(type==='delete')return void act({action:'remove',table:modal.table,id:row.id});
 if(type==='registry'){
  const table=modal.table;const acts:Record<string,string>={classes:'class',groups:'group',students:'student',weeks:'weeks',evaluators:'evaluator',assignments:'assignment'};
  if(row){let changes:Row={};if(table==='classes')changes={name:form.name,grade:Number(form.grade),year:Number(form.year)};if(table==='groups')changes={name:form.name,start_week:form.startWeek};if(table==='students')changes={name:form.name,group_id:form.groupId||null};if(table==='evaluators')changes={name:form.name,email:form.email};if(table==='weeks')changes={start:form.start,due_at:new Date(form.due_at+'-03:00').toISOString()};if(table==='assignments')changes={stage:form.stage,evaluator_id:form.evaluatorId};return void act({action:'edit',table,id:row.id,changes});}
  return void act({action:acts[table],...form,grade:Number(form.grade),year:Number(form.year)});
 }
 }
 function rowActions(table:string,row:Row){return <div className="row-actions"><button title="Editar cadastro" onClick={()=>open('registry',row,{table})}><Pencil size={16}/></button>{'active' in row&&<button title={row.active?'Inativar cadastro':'Reativar cadastro'} onClick={()=>open('toggle',row,{table})}>{row.active?'Inativar':'Reativar'}</button>}<button title="Excluir cadastro" onClick={()=>open('delete',row,{table})}><Trash2 size={16}/></button></div>;}
 if(loading)return <div className="loading"><span className="brand-icon">A</span><h1>Carregando acompanhamento</h1><p>Consultando os registros da escola…</p></div>;
 if(!d.classes.length&&error)return <div className="loading"><h1>Acompanhamento de projetos</h1><p role="alert">{error}</p>{authRequired?<a className="primary-link" href="/signin-with-chatgpt?return_to=%2F" target="_top">Entrar com ChatGPT</a>:<Button onClick={()=>load(true)}>Tentar novamente</Button>}</div>;
 return <div className="workspace"><aside className="sidebar"><div className="brand"><span className="brand-icon">A</span><div><strong>ASN Projetos</strong><small>Informática para Web</small></div></div><p className="nav-label">ACOMPANHAMENTO · 2026</p><nav>{nav.filter(([key])=>admin||!['registry','rubrics','grades'].includes(key)).map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={19}/>{label}</button>)}</nav><div className="school"><strong>Antonio do Santos Neves</strong><p>Ensino Médio Integrado</p><span>{admin?'Coordenação':'Área do avaliador'}</span></div></aside>
 <div className="main"><header className="topbar"><span>Projetos interdisciplinares <b>/</b> 3º trimestre</span><div className="user"><span className="avatar">{d.user.name?.slice(0,1).toUpperCase()}</span><span>{d.user.email}<small>{admin?'Coordenador':'Avaliador'}</small></span><a href="/signout-with-chatgpt?return_to=%2F" title="Sair" target="_top"><LogOut size={17}/></a></div></header>
 <main><div className="page-title"><div><p className="eyebrow">{name('classes',classId)} · 2026</p><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div><div className="actions"><button className="subtle" onClick={()=>load()} title="Atualizar dados"><RefreshCw size={16}/><span>Atualizar</span></button>{admin&&['dashboard','weeks','tasks'].includes(tab)&&<Button onClick={()=>open('report')}><Plus size={17}/>Relatório semanal</Button>}</div></div>
 {error&&<div className="alert error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Fechar mensagem"><X size={16}/></button></div>}{notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}
 {filters}{['dashboard','weeks','written','assessments','grades'].includes(tab)&&studentId&&<p className="footnote">O filtro de estudante afeta as atividades e as notas individuais. Registros e fichas coletivas continuam vinculados ao grupo.</p>}
 {tab==='dashboard'&&<><div className="metric-grid"><div className="metric accent"><span>Relatórios registrados</span><strong>{matrix.filter((x:Row)=>x.r).length}<small> / {matrix.length}</small></strong><p>Grupos × semanas cadastradas</p></div><div className="metric"><span>Planejamentos conferidos</span><strong>{matrix.filter((x:Row)=>x.r?.plan_checked_at).length}</strong><p>{matrix.filter((x:Row)=>x.r&&!x.r.plan_checked_at).length} aguardando conferência</p></div><div className="metric"><span>Atividades cumpridas</span><strong>{done}<small> / {done+missed+pending}</small></strong><p>{pending} atividades a conferir</p></div><div className="metric"><span>Relatórios atrasados</span><strong>{matrix.filter((x:Row)=>!x.r&&x.late).length}</strong><p>Prazo encerrado, sem registro</p></div></div>
 <div className="chart-grid"><section className="panel"><div className="section-title"><h2>Atividades por grupo</h2><span>Quantidade</span></div>{chartData.length?<ResponsiveContainer width="100%" height={260}><BarChart data={chartData} barSize={36}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Bar dataKey="Cumpriu" stackId="a" fill="#169579"/><Bar dataKey="Não cumpriu" stackId="a" fill="#d65a63"/><Bar dataKey="A conferir" stackId="a" fill="#e5ad39" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer>:<Empty>Cadastre os grupos para começar.</Empty>}</section><section className="panel"><div className="section-title"><h2>Evolução semanal</h2><span>Avaliações de 0 a 100%</span></div>{trend.some((x:Row)=>x['Desempenho (%)']!==null)?<ResponsiveContainer width="100%" height={260}><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis domain={[0,100]}/><Tooltip/><Line dataKey="Desempenho (%)" stroke="#3367cd" strokeWidth={3} connectNulls={false}/></LineChart></ResponsiveContainer>:<Empty>O gráfico aparecerá quando as atividades forem avaliadas.</Empty>}</section></div>
 <section className="panel"><div className="section-title"><div><h2>O que precisa de atenção</h2><p>Relatório, planejamento e verificação das entregas.</p></div><button onClick={()=>setTab('weeks')}>Ver todas as semanas <ArrowUpRight size={16}/></button></div><div className="attention-list">{matrix.filter((x:Row)=>!x.r||!x.r.plan_checked_at||!x.checked).slice(0,6).map((x:Row)=><button key={x.w.id+x.g.id} onClick={()=>x.r?open('detail',x.r):admin&&open('report',undefined,{groupId:x.g.id,weekId:x.w.id})}><span className="group-mark">{x.g.name.replace('Grupo ','G')}</span><div><strong>{x.g.name}</strong><span>Semana de {day(x.w.start)}</span></div><Badge>{!x.r?(x.late?'Relatório atrasado':'Relatório pendente'):!x.r.plan_checked_at?'Conferir planejamento':'Conferir entregas'}</Badge><ArrowUpRight size={18}/></button>)}{!matrix.length&&<Empty>Cadastre o calendário de semanas para controlar as entregas.</Empty>}{matrix.length>0&&matrix.every((x:Row)=>x.r?.plan_checked_at&&x.checked)&&<p className="success-text">Todas as semanas do filtro estão conferidas.</p>}</div></section></>}
 {tab==='weeks'&&<section className="panel"><div className="section-title"><div><h2>Controle semanal</h2><p>Horários de Brasília. Confira o calendário completo do trimestre.</p></div>{admin&&<Button onClick={()=>open('registry',undefined,{table:'weeks'})}><Plus size={16}/>Cadastrar semanas</Button>}</div><div className="table-wrap"><table><thead><tr><th>Semana / grupo</th><th>Prazo</th><th>Relatório</th><th>Planejamento</th><th>Entregas conferidas</th><th>Ações</th></tr></thead><tbody>{matrix.map((x:Row)=><tr key={x.w.id+x.g.id}><td><strong>{x.g.name}</strong><small>{day(x.w.start)}</small></td><td>{fmt(x.w.due_at)}</td><td>{x.r?<><Badge status="done">{x.r.imported_at?'Importado':'Enviado'}</Badge><small>{x.r.submitted_at?fmt(x.r.submitted_at):'Horário original desconhecido'}</small></>:<Badge status={x.late?'missed':'pending'}>{x.late?'Atrasado':'Não enviado'}</Badge>}</td><td><Badge status={x.r?.plan_checked_at?'done':'pending'}>{x.r?.plan_checked_at?'Conferido':'Pendente'}</Badge>{x.r?.plan_checked_at&&<small>{fmt(x.r.plan_checked_at)}</small>}</td><td><Badge status={x.checked?'done':'pending'}>{x.checked?'Todas conferidas':'Conferência pendente'}</Badge></td><td>{x.r?<button className="text-button" onClick={()=>open('detail',x.r)}>Abrir relatório</button>:admin&&<button className="text-button" onClick={()=>open('report',undefined,{groupId:x.g.id,weekId:x.w.id})}>Registrar</button>}</td></tr>)}</tbody></table></div>{!matrix.length&&<Empty>Cadastre grupos e semanas para gerar a matriz de acompanhamento.</Empty>}</section>}
 {tab==='tasks'&&<section className="panel"><div className="section-title"><h2>Responsabilidades individuais</h2><button onClick={()=>exportCSV('atividades',taskRows.map((t:Row)=>({Estudante:t.student,Grupo:t.group,Semana:t.week,Atividade:t.description,Situacao:statuses[t.status],Percentual:t.percent,Justificativa:t.justification,Conferido:fmt(t.reviewed_at)})))}><Download size={16}/>Exportar CSV</button></div><div className="inline-filters"><input aria-label="Pesquisar atividades" placeholder="Pesquisar estudante ou atividade…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filtrar situação" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todas as situações</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Estudante</th><th>Atividade</th><th>Situação</th><th>Avaliação</th><th>Justificativa / evidência</th><th>Conferência</th></tr></thead><tbody>{taskRows.map((t:Row)=><tr key={t.id}><td><strong>{t.student}</strong><small>{t.group} · {day(t.week)}</small></td><td className="long">{t.description}</td><td><Badge status={t.status}/></td><td>{t.percent===null?'—':num(t.percent,1)+'%'}</td><td className="long">{t.justification||'—'}{t.evidence&&<small>{t.evidence}</small>}</td><td>{t.status!=='none'&&canWeekly(t.groupId)&&<button className="text-button" onClick={()=>open('review',t,{table:'tasks'})}>{t.reviewed_at?'Revisar':'Conferir'}</button>}<small>{t.reviewed_at?fmt(t.reviewed_at):''}</small></td></tr>)}</tbody></table></div>{!tasks.length&&<Empty>Nenhuma atividade neste filtro.</Empty>}</section>}
 {tab==='written'&&<><div className="info">Envie versões do trabalho em PDF ou DOCX (até 20 MB). Cada envio guarda data e hora. Uma nova versão precisa de novas fichas de avaliação.</div><div className="cards-grid">{selectedGroups.map((g:Row)=>{const files=d.files.filter((f:Row)=>f.group_id===g.id).sort((a:Row,b:Row)=>b.uploaded_at.localeCompare(a.uploaded_at));return <section className="panel" key={g.id}><div className="section-title"><h2>{g.name}</h2>{admin&&<button onClick={()=>{open('upload');setForm({groupId:g.id});}}><Upload size={16}/>Enviar versão</button>}</div>{files.length?files.map((f:Row,i:number)=><a className="file-row" key={f.id} href={'/api/files?id='+encodeURIComponent(f.id)}><FileText size={24}/><div><strong>{f.name}</strong><small>{fmt(f.uploaded_at)} · {num(f.size/1024,0)} KB{!i?' · Versão atual':''}</small></div><Download size={18}/></a>):<Empty>O grupo ainda não enviou o trabalho escrito.</Empty>}</section>;})}</div></>}
 {tab==='assessments'&&<><div className="info">Cada avaliador preenche a própria ficha. Critérios de 0 a 100% são ponderados e convertidos nos pontos da área. As fichas da banca têm o mesmo peso entre si.</div><div className="cards-grid">{d.assignments.filter((a:Row)=>a.active===1&&selectedGroups.some((g:Row)=>g.id===a.group_id)).map((a:Row)=>{const ev=d.evaluators.find((e:Row)=>e.id===a.evaluator_id),result=d.assessments.filter((x:Row)=>x.assignment_id===a.id).sort((x:Row,y:Row)=>y.submitted_at.localeCompare(x.submitted_at))[0],file=d.files.filter((f:Row)=>f.group_id===a.group_id).sort((x:Row,y:Row)=>y.uploaded_at.localeCompare(x.uploaded_at))[0];const valid=result&&(a.stage!=='written'||result.file_id===file?.id);return <section className="panel assessment-card" key={a.id}><div className="section-title"><span className="eyebrow">{name('groups',a.group_id)}</span><Badge status={valid?'done':'pending'}>{valid?'Ficha registrada':'Pendente'}</Badge></div><h2>{stageLabel(a.stage)}</h2><p>{ev?.name}</p><small>{ev?.email}</small>{a.stage==='weekly'?<Button variant="outline" onClick={()=>setTab('tasks')}>Abrir conferência semanal</Button>:<><div className="score-preview"><strong>{valid?num(result.percent,1)+'%':'—'}</strong><span>{valid?fmt(result.submitted_at):'Aguardando avaliação'}</span></div>{ev?.email===d.user.email?<Button disabled={!rubric} onClick={()=>open('assessment',a)}>{result?'Preencher nova revisão':'Preencher ficha'}</Button>:<p className="muted">Preenchimento pelo avaliador designado.</p>}</>}</section>;})}</div>{!d.assignments.some((a:Row)=>a.active===1&&selectedGroups.some((g:Row)=>g.id===a.group_id))&&<Empty>{admin?'Cadastre avaliadores e vincule cada um a uma área e grupo em Cadastros.':'Você ainda não tem fichas atribuídas nesta turma.'}</Empty>}</>}
 {tab==='grades'&&<section className="panel"><div className="section-title"><div><h2>Consolidação do trimestre</h2><p>{rubric?'Total: '+num(rubric.total)+' pontos. As notas parciais não substituem a nota final.':'Configure os pontos do trimestre antes de avaliar.'}</p></div><button onClick={()=>exportCSV('notas-trimestre',gradeRows.map(({s,grade}:any)=>({Estudante:s.name,Grupo:name('groups',s.group_id),...Object.fromEntries(grade.parts.map((p:Row)=>[stageLabel(p.stage),p.points===null?'':num(p.points)])),Total:grade.total===null?'':num(grade.total),Situacao:grade.complete?'Finalizada':'Parcial / pendente'})))}><Download size={16}/>Exportar notas</button></div><div className="table-wrap"><table><thead><tr><th>Estudante</th>{stages.map(s=><th key={s.id}>{s.name}</th>)}<th>Total</th><th>Situação</th></tr></thead><tbody>{gradeRows.map(({s,grade}:any)=><tr key={s.id}><td><strong>{s.name}</strong><small>{name('groups',s.group_id)}</small></td>{stages.map(x=>{const p=grade.parts.find((p:Row)=>p.stage===x.id);return <td key={x.id}>{num(p?.points)}<small>{p&&!p.complete?p.pending:''}</small></td>;})}<td><strong>{num(grade.total)}</strong><small>de {num(grade.max)}</small></td><td><Badge status={grade.complete?'done':'pending'}>{grade.complete?'Finalizada':'Parcial / pendente'}</Badge></td></tr>)}</tbody></table></div><p className="footnote">Acompanhamento individual + escrito + apresentação + aplicativo. Uma área só fica concluída quando todas as conferências ou fichas previstas estão registradas. O filtro de semana não altera a nota do trimestre.</p></section>}
 {tab==='registry'&&admin&&<section className="panel"><div className="section-title"><h2>Organização das turmas</h2><Button onClick={()=>open('registry',undefined,{table:registry})}><Plus size={17}/>Novo cadastro</Button></div><div className="tabs">{[['students','Estudantes'],['groups','Grupos'],['classes','Turmas'],['weeks','Semanas'],['evaluators','Avaliadores'],['assignments','Vínculos de avaliação']].map(([k,v])=><button className={registry===k?'selected':''} key={k} onClick={()=>setRegistry(k)}>{v}</button>)}</div>{registry==='evaluators'&&<div className="info">Cadastre o e-mail usado pelo avaliador no ChatGPT. Depois vincule as áreas em “Vínculos de avaliação”. O acesso ao site também precisa ser liberado no compartilhamento do Sites.</div>}<div className="table-wrap"><table><thead><tr><th>Cadastro</th><th>Vínculo / informação</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{d[registry].filter((r:Row)=>registry==='classes'||(registry==='assignments'?groups.some((g:Row)=>g.id===r.group_id):r.class_id===classId)).map((r:Row)=><tr key={r.id}><td><strong>{r.name??(registry==='weeks'?day(r.start):stageLabel(r.stage))}</strong>{r.email&&<small>{r.email}</small>}</td><td>{registry==='students'?name('groups',r.group_id):registry==='classes'?r.grade+'ª série · '+r.year:registry==='weeks'?fmt(r.due_at):registry==='assignments'?name('groups',r.group_id)+' · '+name('evaluators',r.evaluator_id):registry==='groups'?'Desde '+day(r.start_week):name('classes',r.class_id)}</td><td>{'active' in r?<Badge status={r.active?'done':'none'}>{r.active?'Ativo':'Inativo'}</Badge>:'Cadastrada'}</td><td>{rowActions(registry,r)}</td></tr>)}</tbody></table></div></section>}
 {tab==='rubrics'&&admin&&<section className="panel"><div className="section-title"><div><h2>Distribuição da nota</h2><p>Defina a pontuação total e os critérios antes da primeira avaliação.</p></div><Badge status={locked?'none':'pending'}>{locked?'Parâmetros bloqueados':'Configurável'}</Badge></div><div className="allocation"><Field label="Total de pontos do trimestre"><input disabled={locked} type="number" min="0.01" max="1000" step="0.01" value={total} onChange={e=>setTotal(e.target.value)}/></Field><div><span>Soma das áreas</span><strong>{num(stages.reduce((s,x)=>s+Number(config[x.id].points||0),0))} <small>/ {total||'—'}</small></strong></div></div><div className="rubric-grid">{stages.map(s=><div className="rubric" key={s.id}><h3>{s.name}</h3><Field label="Pontos desta área"><input disabled={locked} type="number" min="0" step="0.01" value={config[s.id].points} onChange={e=>setConfig({...config,[s.id]:{...config[s.id],points:Number(e.target.value)}})}/></Field><div className="criteria-head"><span>Critério</span><span>Peso (%)</span></div>{config[s.id].criteria.map((c:Row,i:number)=><div className="criterion" key={c.id}><input aria-label="Nome do critério" disabled={locked||s.id==='weekly'} value={c.name} onChange={e=>{const v=structuredClone(config);v[s.id].criteria[i].name=e.target.value;setConfig(v);}}/><input aria-label="Peso do critério" disabled={locked} type="number" min="0.01" max="100" step="0.01" value={c.weight} onChange={e=>{const v=structuredClone(config);v[s.id].criteria[i].weight=Number(e.target.value);setConfig(v);}}/>{s.id!=='weekly'&&!locked&&<button type="button" title="Excluir critério" onClick={()=>{const v=structuredClone(config);v[s.id].criteria.splice(i,1);setConfig(v);}}><X size={15}/></button>}</div>)}<div className="criterion-total">Pesos: {num(config[s.id].criteria.reduce((s:number,c:Row)=>s+c.weight,0))}%</div>{s.id!=='weekly'&&!locked&&<button className="text-button" onClick={()=>{const v=structuredClone(config);v[s.id].criteria.push({id:crypto.randomUUID(),name:'',weight:0});setConfig(v);}}>+ Adicionar critério</button>}</div>)}</div><div className="info">Conversão: percentual ponderado ÷ 100 × pontos da área. Na banca, a média dos percentuais dos avaliadores define a nota da área. Os pesos iniciais dos critérios são sugestões editáveis; nenhuma pontuação total foi presumida.</div><Button disabled={busy||locked} onClick={()=>{try{validateConfig(Number(total),config);act({action:'rubric',classId,total:Number(total),config},false);}catch(e){setError((e as Error).message);}}}>Salvar parâmetros</Button></section>}
 <footer>EEEFM Antonio do Santos Neves <span>Atualizado às {updated?new Date(updated).toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—'} · Atualização a cada 30 s</span></footer>
 </main></div>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open&&!busy)setModal(null);}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{modal?.type==='review'?'Conferir atividade':modal?.type==='report'?'Relatório da semana':modal?.type==='detail'?'Registro semanal':modal?.type==='assessment'?'Ficha de avaliação':modal?.type==='upload'?'Enviar trabalho escrito':modal?.type==='delete'?'Excluir cadastro':modal?.type==='toggle'?'Alterar situação do cadastro':modal?.row?'Editar cadastro':'Novo cadastro'}</DialogTitle></DialogHeader>
 {modal&&<>{error&&<div className="alert error" role="alert">{error}</div>}{modal.type==='detail'?<div className="report-detail"><Badge>{name('groups',modal.row.group_id)}</Badge><p className="muted">{modal.row.submitted_at?'Enviado em '+fmt(modal.row.submitted_at):'Importado em '+fmt(modal.row.imported_at)+' · horário original não informado'}</p><h3>O que fizeram na semana passada?</h3><p>{modal.row.past}</p><h3>O que farão nesta semana?</h3><p>{modal.row.plan}</p><h3>O que o grupo vai entregar?</h3><p>{modal.row.delivery}</p><h3>Responsabilidades individuais</h3>{d.tasks.filter((t:Row)=>t.report_id===modal.row.id).map((t:Row)=><div className="detail-task" key={t.id}><strong>{name('students',t.student_id)}</strong><p>{t.description}</p><Badge status={t.status}/></div>)}<h3>Conferência da entrega coletiva</h3><Badge status={modal.row.status}/><p>{modal.row.percent===null?'Sem avaliação':num(modal.row.percent)+'%'} {modal.row.justification&&'· '+modal.row.justification}</p>{admin&&<Button variant="outline" onClick={()=>open('report',modal.row)}>Editar planejamento</Button>}{canWeekly(modal.row.group_id)&&<div className="actions">{!modal.row.plan_checked_at&&<Button disabled={busy} onClick={()=>act({action:'check-plan',id:modal.row.id})}>Confirmar conferência do planejamento</Button>}<Button variant="outline" onClick={()=>open('review',modal.row,{table:'reports'})}>Avaliar entrega do grupo</Button></div>}</div>:modal.type==='toggle'?<><p>{modal.row.active?'Inativar preserva o histórico e retira o cadastro das novas operações.':'Reativar permite usar este cadastro novamente.'}</p><Button disabled={busy} onClick={()=>act({action:'edit',table:modal.table,id:modal.row.id,changes:{active:modal.row.active?0:1}})}>{modal.row.active?'Inativar':'Reativar'}</Button></>:<form onSubmit={submit} className="form-stack">
 {modal.type==='delete'&&<p>Excluir este cadastro? Se houver histórico vinculado, a exclusão será impedida e você poderá inativá-lo.</p>}
 {modal.type==='review'&&<><p>{modal.row.description??modal.row.delivery}</p><Field label="Cumpriu a atividade prometida?"><select value={form.status} onChange={e=>set('status',e.target.value)}><option value="done">Sim</option><option value="missed">Não</option></select></Field><Field label="Avaliação da atividade (0 a 100%)"><input required type="number" min="0" max="100" step="0.1" value={form.percent} onChange={e=>set('percent',e.target.value)}/></Field><Field label={'Justificativa'+(form.status==='missed'?' (obrigatória)':' / observação')}><textarea required={form.status==='missed'} value={form.justification} onChange={e=>set('justification',e.target.value)}/></Field><Field label="Evidência ou comentário"><textarea value={form.evidence} onChange={e=>set('evidence',e.target.value)}/></Field><p className="muted">A data, a hora e o avaliador serão registrados no envio.</p></>}
 {modal.type==='report'&&<><Field label="Grupo"><select required disabled={!!modal.row} value={form.groupId} onChange={e=>set('groupId',e.target.value)}><option value="">Selecione</option>{groups.filter((g:Row)=>g.active).map((g:Row)=><option key={g.id} value={g.id}>{g.name}</option>)}</select></Field><Field label="Semana"><select required disabled={!!modal.row} value={form.weekId} onChange={e=>set('weekId',e.target.value)}><option value="">Selecione</option>{weeks.map((w:Row)=><option key={w.id} value={w.id}>{day(w.start)}</option>)}</select></Field>{[['past','O que fizeram na semana passada?'],['plan','O que farão nesta semana?'],['delivery','O que o grupo vai entregar no final da semana?']].map(([k,label])=><Field key={k} label={label}><textarea required value={form[k]} onChange={e=>set(k,e.target.value)}/></Field>)}<h3>O que cada integrante fará nesta semana?</h3>{d.students.filter((s:Row)=>s.group_id===form.groupId&&s.active===1).map((s:Row)=><div className="member-task" key={s.id}><Field label={s.name}><textarea required={!form.tasks[s.id]?.none} disabled={form.tasks[s.id]?.none} value={form.tasks[s.id]?.description??''} onChange={e=>set('tasks',{...form.tasks,[s.id]:{...form.tasks[s.id],description:e.target.value}})}/></Field><label className="checkbox"><input type="checkbox" checked={!!form.tasks[s.id]?.none} onChange={e=>set('tasks',{...form.tasks,[s.id]:{...form.tasks[s.id],none:e.target.checked}})}/>Sem tarefa atribuída</label></div>)}</>}
 {modal.type==='upload'&&<><Field label="Grupo"><select required value={form.groupId??''} onChange={e=>set('groupId',e.target.value)}><option value="">Selecione</option>{groups.map((g:Row)=><option key={g.id} value={g.id}>{g.name}</option>)}</select></Field><Field label="Documento PDF ou DOCX"><input required type="file" accept=".pdf,.docx" onChange={e=>set('file',e.target.files?.[0])}/></Field><p>Até 20 MB. O arquivo anterior permanece no histórico.</p></>}
 {modal.type==='assessment'&&(()=>{const group=d.groups.find((g:Row)=>g.id===modal.row.group_id);const r=d.rubrics.find((r:Row)=>r.class_id===group.class_id),cfg=r?JSON.parse(r.config)[modal.row.stage]:null;let pct=null;try{pct=cfg?percentScore(cfg.criteria,form.scores):null;}catch{}return <><p><strong>{name('groups',modal.row.group_id)}</strong> · {stageLabel(modal.row.stage)}</p>{cfg?.criteria.map((c:Row)=><Field key={c.id} label={`${c.name} · peso ${c.weight}%`}><input required type="number" min="0" max="100" step="0.1" placeholder="0 a 100%" value={form.scores[c.id]??''} onChange={e=>set('scores',{...form.scores,[c.id]:e.target.value===''?undefined:Number(e.target.value)})}/></Field>)}<div className="score-preview"><strong>{pct===null?'—':num(pct,1)+'%'}</strong><span>{pct===null?'Preencha todos os critérios':num(pct/100*cfg.points)+' de '+num(cfg.points)+' pontos'}</span></div><Field label="Parecer do avaliador"><textarea value={form.notes} onChange={e=>set('notes',e.target.value)}/></Field><p className="muted">A ficha será registrada em seu nome: {d.user.email}. Revisões preservam as fichas anteriores.</p></>;})()}
 {modal.type==='registry'&&<>{!modal.row&&modal.table!=='classes'&&<Field label="Turma"><select required value={form.classId} onChange={e=>{set('classId',e.target.value);set('groupId','');}}>{d.classes.filter((c:Row)=>c.active).map((c:Row)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>}{['classes','groups','students','evaluators'].includes(modal.table)&&<Field label="Nome"><input required value={form.name??''} onChange={e=>set('name',e.target.value)}/></Field>}{modal.table==='classes'&&<><Field label="Série"><select value={form.grade} onChange={e=>set('grade',Number(e.target.value))}>{[1,2,3].map(i=><option key={i} value={i}>{i}ª série</option>)}</select></Field><Field label="Ano"><input required type="number" min="2026" max="2100" value={form.year} onChange={e=>set('year',Number(e.target.value))}/></Field></>}{modal.table==='groups'&&<Field label="Primeira semana de acompanhamento (segunda-feira)"><input required type="date" value={form.startWeek} onChange={e=>set('startWeek',e.target.value)}/></Field>}{['students','assignments'].includes(modal.table)&&<Field label="Grupo"><select required={modal.table==='assignments'} disabled={!!modal.row&&modal.table==='assignments'} value={form.groupId} onChange={e=>set('groupId',e.target.value)}><option value="">Sem grupo</option>{d.groups.filter((g:Row)=>g.class_id===form.classId&&g.active).map((g:Row)=><option key={g.id} value={g.id}>{g.name}</option>)}</select></Field>}{modal.table==='evaluators'&&<Field label="E-mail usado para entrar no ChatGPT"><input required type="email" value={form.email??''} onChange={e=>set('email',e.target.value)}/></Field>}{modal.table==='assignments'&&<><Field label="Avaliador"><select required value={form.evaluatorId} onChange={e=>set('evaluatorId',e.target.value)}><option value="">Selecione</option>{d.evaluators.filter((e:Row)=>e.class_id===form.classId&&e.active).map((e:Row)=><option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><Field label="Área de responsabilidade"><select value={form.stage} onChange={e=>set('stage',e.target.value)}>{stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field></>}{modal.table==='weeks'&&<><Field label="Semana inicial (segunda-feira)"><input required type="date" value={form.start} onChange={e=>set('start',e.target.value)}/></Field>{modal.row?<Field label="Prazo de entrega"><input required type="datetime-local" value={form.due_at?.slice(0,16)??''} onChange={e=>set('due_at',e.target.value)}/></Field>:<><Field label="Semana final (segunda-feira)"><input required type="date" value={form.end} onChange={e=>set('end',e.target.value)}/></Field><p className="muted">Serão criadas todas as semanas do intervalo, com prazo na sexta-feira às 17h de Brasília. Depois, você pode editar o prazo de cada semana.</p></>}</>}</>}
 <div className="modal-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setModal(null)}>Cancelar</Button><Button type="submit" disabled={busy}>{busy?'Salvando…':modal.type==='delete'?'Excluir':modal.type==='assessment'?'Concluir ficha':modal.type==='report'?(modal.row?'Salvar revisão':'Enviar relatório'):'Salvar'}</Button></div>
 </form>}</>}
 </DialogContent></Dialog>
 </div>;
}
