export const stages=[{id:'weekly',name:'Acompanhamento semanal'},{id:'written',name:'Trabalho escrito'},{id:'presentation',name:'Apresentação'},{id:'app',name:'Aplicativo'}];
export const statuses:Record<string,string>={pending:'A conferir',done:'Cumpriu',missed:'Não cumpriu',none:'Sem tarefa'};
export const emptyData={classes:[],groups:[],students:[],weeks:[],reports:[],tasks:[],audit:[],rubrics:[],evaluators:[],assignments:[],files:[],assessments:[],representatives:[],participation:[],user:{admin:false,email:'',name:''}};
export const defaultConfig=()=>({weekly:{points:0,criteria:[{id:'individual',name:'Atividades individuais',weight:50},{id:'collective',name:'Entrega coletiva',weight:30},{id:'peer',name:'Participação informada pelo grupo',weight:20}],peerMode:'individual',peerCriteria:[{id:'participation',name:'Participação e colaboração',weight:50},{id:'fulfillment',name:'Cumprimento das tarefas assumidas',weight:50}]},written:{points:0,criteria:[{id:'content',name:'Conteúdo e fundamentação',weight:40},{id:'organization',name:'Organização e coerência',weight:30},{id:'format',name:'Escrita e apresentação do documento',weight:30}]},presentation:{points:0,criteria:[{id:'mastery',name:'Domínio do conteúdo',weight:40},{id:'clarity',name:'Clareza e organização',weight:30},{id:'participation',name:'Participação e respostas à banca',weight:30}]},app:{points:0,criteria:[{id:'function',name:'Funcionamento e requisitos',weight:40},{id:'data',name:'Importação e tratamento dos dados',weight:30},{id:'usability',name:'Usabilidade e testes',weight:30}]}});
export function validateConfig(total:number,config:any){if(!Number.isFinite(total)||total<=0||total>1000)throw Error('Informe o total de pontos do trimestre entre 0,01 e 1.000.');let sum=0;for(const s of stages){const x=config?.[s.id];if(!x||!Number.isFinite(x.points)||x.points<0)throw Error('Informe os pontos de todas as áreas.');sum+=x.points;if(!Array.isArray(x.criteria)||!x.criteria.length||x.criteria.length>20||new Set(x.criteria.map((c:any)=>c.id)).size!==x.criteria.length)throw Error('Cadastre critérios distintos em cada área.');if(x.criteria.some((c:any)=>!c.id||!c.name?.trim()||!Number.isFinite(c.weight)||c.weight<0)||Math.abs(x.criteria.reduce((a:number,c:any)=>a+c.weight,0)-100)>0.00001)throw Error('Os pesos dos critérios de cada área devem somar 100%.');}if(Math.abs(sum-total)>0.00001)throw Error('A soma das áreas deve ser exatamente igual aos pontos do trimestre.');if(config.weekly.criteria.map((c:any)=>c.id).sort().join(',')!=='collective,individual,peer')throw Error('No acompanhamento, mantenha os critérios individual, coletivo e participação.');}
export function validatePeer(config:any){if(!['individual','collective'].includes(config.weekly.peerMode))throw Error('Escolha a modalidade da participação.');const c=config.weekly.peerCriteria;if(!Array.isArray(c)||c.length!==2||c.map((x:any)=>x.id).sort().join(',')!=='fulfillment,participation'||c.some((x:any)=>!Number.isFinite(x.weight)||x.weight<0)||Math.abs(c.reduce((n:number,x:any)=>n+x.weight,0)-100)>0.00001)throw Error('Os pesos de participação e cumprimento devem somar 100%.');}
export function percentScore(criteria:any[],scores:any){let sum=0;for(const c of criteria){if(typeof scores?.[c.id]!=='number'||!Number.isFinite(scores[c.id])||scores[c.id]<0||scores[c.id]>100)throw Error('Preencha todos os critérios com valores de 0 a 100%.');sum+=scores[c.id]*c.weight/100;}return sum;}
export function groupStage(d:any,groupId:string,stage:string){const group=d.groups.find((g:any)=>g.id===groupId);const rubric=d.rubrics.find((r:any)=>r.class_id===group?.class_id);if(!rubric)return {percent:null,points:null,complete:false,pending:'Sem parâmetros'};const config=JSON.parse(rubric.config)[stage];if(config.points===0)return {percent:0,points:0,complete:true,pending:''};const panel=d.assignments.filter((x:any)=>x.group_id===groupId&&x.stage===stage&&x.active===1);const file=d.files.filter((f:any)=>f.group_id===groupId).sort((a:any,b:any)=>b.uploaded_at.localeCompare(a.uploaded_at))[0];const vals=panel.map((p:any)=>d.assessments.filter((a:any)=>a.assignment_id===p.id&&(stage!=='written'||a.file_id===file?.id)).sort((a:any,b:any)=>b.submitted_at.localeCompare(a.submitted_at))[0]).filter(Boolean);const percent=vals.length?vals.reduce((s:number,v:any)=>s+v.percent,0)/vals.length:null;const complete=panel.length>0&&vals.length===panel.length&&(stage!=='written'||!!file);return {percent,points:percent===null?null:percent/100*config.points,complete,pending:!panel.length?'Banca não definida':`${vals.length}/${panel.length} fichas`};}
export function weeklyScore(d:any,student:any,config:any){const group=d.groups.find((g:any)=>g.id===student.group_id);if(!group)return {percent:null,points:null,complete:false,pending:'Sem grupo'};if(config.points===0)return {percent:0,points:0,complete:true,pending:''};const weeks=d.weeks.filter((w:any)=>w.class_id===student.class_id&&w.start>=group.start_week);const reports=weeks.map((w:any)=>d.reports.find((r:any)=>r.week_id===w.id&&r.group_id===group.id));const tasks=reports.map((r:any)=>r&&d.tasks.find((t:any)=>t.report_id===r.id&&t.student_id===student.id));const assigned=tasks.filter((t:any)=>t&&t.status!=='none');const evaluated=assigned.filter((t:any)=>t.percent!==null&&t.percent!==undefined);const collective=reports.filter((r:any)=>r&&r.percent!==null&&r.percent!==undefined);const individual=evaluated.length?evaluated.reduce((s:number,t:any)=>s+t.percent,0)/evaluated.length:null;const team=collective.length?collective.reduce((s:number,r:any)=>s+r.percent,0)/collective.length:null;const peers=reports.map((r:any)=>r?(d.participation??[]).filter((p:any)=>p.report_id===r.id).sort((a:any,b:any)=>b.submitted_at.localeCompare(a.submitted_at))[0]:null);const peerValues=peers.map((p:any)=>p?JSON.parse(p.percentages)[p.mode==='collective'?'group':student.id]:undefined).filter((n:any)=>typeof n==='number');const peer=peerValues.length?peerValues.reduce((a:number,b:number)=>a+b,0)/peerValues.length:null;
 const weights=Object.fromEntries(config.criteria.map((c:any)=>[c.id,c.weight]));const scores:any={individual,collective:team,peer};const hasScores=config.criteria.every((c:any)=>c.weight===0||scores[c.id]!==null);const percent=hasScores?config.criteria.reduce((n:number,c:any)=>n+(scores[c.id]??0)*c.weight/100,0):null;
 const complete=weeks.length>0&&reports.every((r:any)=>r?.plan_checked_at)&&(weights.collective===0||reports.every((r:any)=>r?.reviewed_at))&&(weights.individual===0||(tasks.every((t:any)=>t&&(t.status==='none'||t.reviewed_at))&&individual!==null))&&(weights.peer===0||peerValues.length===weeks.length)&&hasScores;
 return {percent,points:percent===null?null:percent/100*config.points,complete,pending:`${evaluated.length}/${assigned.length} atividades · ${peerValues.length}/${weeks.length} participações`};}

export function studentGrade(d:any,s:any){const r=d.rubrics.find((r:any)=>r.class_id===s.class_id);if(!r)return {parts:[],total:null,complete:false,max:null};const c=JSON.parse(r.config);const parts=[{stage:'weekly',...weeklyScore(d,s,c.weekly)},...stages.slice(1).map(x=>({stage:x.id,...groupStage(d,s.group_id,x.id)}))];return {parts,total:parts.some(x=>x.points!==null)?parts.reduce((n,x)=>n+(x.points??0),0):null,complete:parts.every(x=>x.complete),max:r.total};}
